'use client';

import React, { useState } from 'react';
import { RepurposeResponse } from '@/types';
import {
  MessageSquare,
  Send,
  Copy,
  Check,
  Download,
  ArrowUpRight,
  Layers,
  Video,
} from 'lucide-react';
import { TwitterXIcon, LinkedInIcon } from '@/components/icons/PlatformIcons';
import { CarouselDeckPreview } from '@/components/CarouselDeckPreview';
import { VideoScriptPreview } from '@/components/VideoScriptPreview';

interface OutputGridProps {
  data: RepurposeResponse;
}

export function OutputGrid({ data }: OutputGridProps) {
  const [activeTab, setActiveTab] = useState<
    'twitter' | 'quora' | 'linkedin' | 'whatsapp' | 'carousel' | 'video'
  >('twitter');
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  const copyToClipboard = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const handleDownloadMarkdown = () => {
    const mdContent = `# ContentPulse AI Repurposed Assets
**Source Article**: ${data.sourceTitle}
**Source URL**: ${data.extractedUrl || 'N/A'}
**Generated At**: ${new Date().toISOString()}
**Original Word Count**: ${data.originalWordCount} words

---

## 1. Twitter / X Viral Thread (5 Tweets)
${data.outputs.twitter.fullThreadText}

**Hashtags**: ${data.outputs.twitter.hashtags.join(' ')}

---

## 2. Quora High-Authority Answer
### Question: ${data.outputs.quora.suggestedQuestion}

${data.outputs.quora.answerText}

**Key Highlights**:
${data.outputs.quora.keyBulletPoints.map((b) => `- ${b}`).join('\n')}

**Source Reference**:
${data.outputs.quora.backlinkCitation}

---

## 3. LinkedIn B2B Thought-Leadership Post
${data.outputs.linkedin.fullPostText}

**Hashtags**: ${data.outputs.linkedin.hashtags.join(' ')}

---

## 4. WhatsApp / Telegram Channel Executive Briefing
${data.outputs.whatsapp.fullMessageText}

---

## 5. LinkedIn Slide Carousel (5 Slides)
${data.outputs.carousel.slides
  .map(
    (s) =>
      `### Slide ${s.slideNumber}: ${s.headline}\n${s.subtext}\n${
        s.keyPoints ? s.keyPoints.map((p) => `- ${p}`).join('\n') : ''
      }\n*${s.footerTag || ''}*`
  )
  .join('\n\n')}

---

## 6. 60-Second Short / Reel Video Script
**Title**: ${data.outputs.videoScript.title}
**Hook**: ${data.outputs.videoScript.hook}

${data.outputs.videoScript.scenes
  .map(
    (sc, i) =>
      `### Scene ${i + 1} (${sc.timeframe})\n- **Visual**: ${sc.visualPrompt}\n- **Overlay Text**: ${sc.onScreenText}\n- **Voiceover**: "${sc.voiceoverText}"`
  )
  .join('\n\n')}

**Voiceover Script**:\n${data.outputs.videoScript.fullVoiceover}

---
*Generated by ContentPulse AI — Multi-Platform Micro-SaaS by Malik Hammad (NEXUS PULSE)*
`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    const sanitizedTitle = data.sourceTitle.toLowerCase().replace(/[^a-z0-9]/g, '-').slice(0, 30);
    link.setAttribute('download', `contentpulse-${sanitizedTitle || 'repurposed'}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleCopyAll = () => {
    const allText = `=== TWITTER / X THREAD ===\n${data.outputs.twitter.fullThreadText}\n\n=== QUORA ANSWER ===\n${data.outputs.quora.answerText}\n\n=== LINKEDIN POST ===\n${data.outputs.linkedin.fullPostText}\n\n=== WHATSAPP / TELEGRAM ===\n${data.outputs.whatsapp.fullMessageText}\n\n=== 60S REEL VOICEOVER ===\n${data.outputs.videoScript.fullVoiceover}`;
    copyToClipboard(allText, 'copy-all');
  };

  const { twitter, quora, linkedin, whatsapp, carousel, videoScript } = data.outputs;

  return (
    <div id="results-section" className="w-full max-w-5xl mx-auto px-4 sm:px-6 mb-16 animate-in fade-in duration-300">
      
      {/* Top Bar with Title, Stats & Global Exports */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
        <div>
          <div className="flex items-center gap-2">
            <span className="p-1 rounded-md bg-emerald-500/20 text-emerald-400">
              <Check className="w-4 h-4" />
            </span>
            <h2 className="text-xl sm:text-2xl font-bold text-white font-[family-name:var(--font-outfit)]">
              Viral Assets Ready (6 Formats)
            </h2>
            <span className="text-xs px-2.5 py-0.5 rounded-full bg-violet-500/20 text-violet-300 border border-violet-500/30">
              {data.processingTimeMs ? `${(data.processingTimeMs / 1000).toFixed(1)}s` : '5s'} pulse
            </span>
          </div>
          <p className="text-xs sm:text-sm text-slate-400 mt-1 line-clamp-1">
            Source: <span className="text-slate-200 font-medium">{data.sourceTitle}</span> ({data.originalWordCount} words processed)
          </p>
        </div>

        {/* Global Action Buttons */}
        <div className="flex items-center gap-2.5 flex-wrap">
          <button
            onClick={handleCopyAll}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold bg-slate-900/80 border border-slate-700 text-slate-200 hover:border-slate-600 hover:text-white transition-all cursor-pointer"
          >
            {copiedKey === 'copy-all' ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                <span className="text-emerald-400">All Formats Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-slate-400" />
                <span>Copy All Formats</span>
              </>
            )}
          </button>

          <button
            onClick={handleDownloadMarkdown}
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-semibold bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500 text-white shadow-md shadow-violet-600/20 transition-all cursor-pointer"
          >
            <Download className="w-3.5 h-3.5 text-white" />
            <span>Download All (.md)</span>
          </button>
        </div>
      </div>

      {/* Main Tabbed Container */}
      <div className="glass-panel-glow rounded-3xl border border-violet-500/20 overflow-hidden shadow-2xl">
        
        {/* Navigation Tabs Header (6 Platforms) */}
        <div className="grid grid-cols-3 sm:grid-cols-6 border-b border-slate-800 bg-[#0B0F19]/90">
          
          {/* Tab 1: Twitter */}
          <button
            onClick={() => setActiveTab('twitter')}
            className={`flex items-center justify-center gap-2 py-4 px-2 text-xs sm:text-sm font-semibold transition-all border-b-2 cursor-pointer ${
              activeTab === 'twitter'
                ? 'border-sky-400 text-sky-400 bg-sky-500/5'
                : 'border-transparent text-slate-400 hover:text-slate-200 hover:bg-slate-800/40'
            }`}
          >
            <TwitterXIcon className="w-4 h-4 text-sky-400" />
            <span className="hidden md:inline">Twitter Thread</span>
            <span className="md:hidden">Twitter</span>
            <span className="text-[10px] px-1 rounded-full bg-sky-500/20 text-sky-300">
              5
            </span>
          </button>

          {/* Tab 2: Quora */}
          <button
            onClick={() => setActiveTab('quora')}
            className={`flex items-center justify-center gap-2 py-4 px-2 text-xs sm:text-sm font-semibold transition-all border-b-2 cursor-pointer ${
              activeTab === 'quora'
                ? 'border-rose-400 text-rose-400 bg-rose-500/5'
                : 'border-transparent text-slate-400 hover:text-slate-200 hover:bg-slate-800/40'
            }`}
          >
            <MessageSquare className="w-4 h-4 text-rose-400" />
            <span>Quora</span>
          </button>

          {/* Tab 3: LinkedIn */}
          <button
            onClick={() => setActiveTab('linkedin')}
            className={`flex items-center justify-center gap-2 py-4 px-2 text-xs sm:text-sm font-semibold transition-all border-b-2 cursor-pointer ${
              activeTab === 'linkedin'
                ? 'border-blue-400 text-blue-400 bg-blue-500/5'
                : 'border-transparent text-slate-400 hover:text-slate-200 hover:bg-slate-800/40'
            }`}
          >
            <LinkedInIcon className="w-4 h-4 text-blue-400" />
            <span>LinkedIn</span>
          </button>

          {/* Tab 4: WhatsApp */}
          <button
            onClick={() => setActiveTab('whatsapp')}
            className={`flex items-center justify-center gap-2 py-4 px-2 text-xs sm:text-sm font-semibold transition-all border-b-2 cursor-pointer ${
              activeTab === 'whatsapp'
                ? 'border-emerald-400 text-emerald-400 bg-emerald-500/5'
                : 'border-transparent text-slate-400 hover:text-slate-200 hover:bg-slate-800/40'
            }`}
          >
            <Send className="w-4 h-4 text-emerald-400" />
            <span className="hidden md:inline">WhatsApp</span>
            <span className="md:hidden">WA</span>
          </button>

          {/* Tab 5: Carousel Slides */}
          <button
            onClick={() => setActiveTab('carousel')}
            className={`flex items-center justify-center gap-2 py-4 px-2 text-xs sm:text-sm font-semibold transition-all border-b-2 cursor-pointer ${
              activeTab === 'carousel'
                ? 'border-violet-400 text-violet-400 bg-violet-500/5'
                : 'border-transparent text-slate-400 hover:text-slate-200 hover:bg-slate-800/40'
            }`}
          >
            <Layers className="w-4 h-4 text-violet-400" />
            <span className="hidden md:inline">Slides (PDF)</span>
            <span className="md:hidden">Slides</span>
            <span className="text-[10px] px-1 rounded-full bg-violet-500/20 text-violet-300">
              5
            </span>
          </button>

          {/* Tab 6: 60s Reel Script */}
          <button
            onClick={() => setActiveTab('video')}
            className={`flex items-center justify-center gap-2 py-4 px-2 text-xs sm:text-sm font-semibold transition-all border-b-2 cursor-pointer ${
              activeTab === 'video'
                ? 'border-amber-400 text-amber-400 bg-amber-500/5'
                : 'border-transparent text-slate-400 hover:text-slate-200 hover:bg-slate-800/40'
            }`}
          >
            <Video className="w-4 h-4 text-amber-400" />
            <span className="hidden md:inline">60s Reel</span>
            <span className="md:hidden">Reel</span>
          </button>

        </div>

        {/* Tab Content Panels */}
        <div className="p-5 sm:p-7">
          
          {/* TAB 1: TWITTER / X */}
          {activeTab === 'twitter' && (
            <div className="space-y-6">
              <div className="flex items-center justify-between flex-wrap gap-3 pb-4 border-b border-slate-800">
                <div>
                  <h3 className="text-base font-bold text-white flex items-center gap-2">
                    <TwitterXIcon className="w-4 h-4 text-sky-400" />
                    <span>5-Tweet Viral Thread Breakdown</span>
                  </h3>
                  <p className="text-xs text-slate-400">
                    Engineered with high-engagement hook, stat metrics, clear takeaways, and conclusion CTA.
                  </p>
                </div>

                <button
                  onClick={() => copyToClipboard(twitter.fullThreadText, 'twitter-full')}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-sky-950/40 border border-sky-500/30 text-sky-300 hover:bg-sky-900/40 transition-colors"
                >
                  {copiedKey === 'twitter-full' ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-sky-400" />
                      <span>Copied Full Thread!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5 text-sky-400" />
                      <span>Copy Complete Thread</span>
                    </>
                  )}
                </button>
              </div>

              {/* Individual Tweet Cards */}
              <div className="space-y-4">
                {twitter.tweets.map((tweet, index) => (
                  <div
                    key={index}
                    className="p-4 sm:p-5 rounded-2xl bg-slate-900/60 border border-slate-800 hover:border-slate-700 transition-all relative group"
                  >
                    <div className="flex items-start justify-between gap-3 mb-2.5">
                      <div className="flex items-center gap-2">
                        <span className="flex items-center justify-center w-6 h-6 rounded-full bg-sky-500/20 text-sky-400 text-xs font-bold">
                          {tweet.tweetNumber}
                        </span>
                        <span className="text-xs font-semibold text-slate-400">
                          {index === 0 ? 'Viral Hook (Tweet 1)' : index === 4 ? 'Conclusion & CTA (Tweet 5)' : `Tweet ${index + 1}`}
                        </span>
                      </div>

                      <div className="flex items-center gap-2">
                        <span className="text-[11px] text-slate-400">
                          {tweet.text.length} / 280 chars
                        </span>
                        <button
                          onClick={() => copyToClipboard(tweet.text, `tweet-${index}`)}
                          className="p-1.5 rounded-lg bg-slate-800 text-slate-400 hover:text-white hover:bg-slate-700 transition-colors"
                          title="Copy this tweet"
                        >
                          {copiedKey === `tweet-${index}` ? (
                            <Check className="w-3.5 h-3.5 text-emerald-400" />
                          ) : (
                            <Copy className="w-3.5 h-3.5" />
                          )}
                        </button>
                      </div>
                    </div>

                    <p className="text-sm text-slate-200 whitespace-pre-line leading-relaxed font-sans">
                      {tweet.text}
                    </p>
                  </div>
                ))}
              </div>

              {/* Hashtag Strip */}
              {twitter.hashtags && twitter.hashtags.length > 0 && (
                <div className="p-3 rounded-xl bg-slate-900/40 border border-slate-800/80 flex items-center gap-2 flex-wrap text-xs">
                  <span className="text-slate-400 font-medium">Recommended Hashtags:</span>
                  {twitter.hashtags.map((tag, idx) => (
                    <span key={idx} className="text-sky-400 font-mono">
                      {tag.startsWith('#') ? tag : `#${tag}`}
                    </span>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* TAB 2: QUORA ANSWER */}
          {activeTab === 'quora' && (
            <div className="space-y-6">
              <div className="flex items-center justify-between flex-wrap gap-3 pb-4 border-b border-slate-800">
                <div>
                  <h3 className="text-base font-bold text-white flex items-center gap-2">
                    <MessageSquare className="w-4 h-4 text-rose-400" />
                    <span>High-Authority Quora Structured Answer</span>
                  </h3>
                  <p className="text-xs text-slate-400">
                    Optimized for search ranking, technical depth, and organic source citation.
                  </p>
                </div>

                <button
                  onClick={() => copyToClipboard(quora.answerText, 'quora-full')}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-rose-950/40 border border-rose-500/30 text-rose-300 hover:bg-rose-900/40 transition-colors"
                >
                  {copiedKey === 'quora-full' ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-rose-400" />
                      <span>Copied Answer!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5 text-rose-400" />
                      <span>Copy Full Answer</span>
                    </>
                  )}
                </button>
              </div>

              <div className="p-4 rounded-2xl bg-rose-950/20 border border-rose-500/30">
                <span className="text-[11px] font-bold uppercase tracking-wider text-rose-400 block mb-1">
                  Target Quora Question:
                </span>
                <p className="text-base font-semibold text-white font-[family-name:var(--font-outfit)]">
                  &ldquo;{quora.suggestedQuestion}&rdquo;
                </p>
              </div>

              <div className="p-5 rounded-2xl bg-slate-900/60 border border-slate-800 space-y-4">
                <p className="text-sm text-slate-200 whitespace-pre-line leading-relaxed">
                  {quora.answerText}
                </p>

                {quora.backlinkCitation && (
                  <div className="mt-4 p-3.5 rounded-xl bg-violet-950/30 border border-violet-500/30 text-xs text-violet-300 flex items-start gap-2.5">
                    <ArrowUpRight className="w-4 h-4 text-violet-400 shrink-0 mt-0.5" />
                    <div>
                      <span className="font-semibold text-white">Backlink Context: </span>
                      {quora.backlinkCitation}
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* TAB 3: LINKEDIN POST */}
          {activeTab === 'linkedin' && (
            <div className="space-y-6">
              <div className="flex items-center justify-between flex-wrap gap-3 pb-4 border-b border-slate-800">
                <div>
                  <h3 className="text-base font-bold text-white flex items-center gap-2">
                    <LinkedInIcon className="w-4 h-4 text-blue-400" />
                    <span>B2B Thought-Leadership LinkedIn Post</span>
                  </h3>
                  <p className="text-xs text-slate-400">
                    Hook + 1-liner spacing + insights + engagement question for high comment velocity.
                  </p>
                </div>

                <button
                  onClick={() => copyToClipboard(linkedin.fullPostText, 'linkedin-full')}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-blue-950/40 border border-blue-500/30 text-blue-300 hover:bg-blue-900/40 transition-colors"
                >
                  {copiedKey === 'linkedin-full' ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-blue-400" />
                      <span>Copied LinkedIn Post!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5 text-blue-400" />
                      <span>Copy Ready-to-Post</span>
                    </>
                  )}
                </button>
              </div>

              <div className="p-6 rounded-2xl bg-slate-900/70 border border-slate-800 space-y-4">
                <div className="flex items-center gap-3 pb-3 border-b border-slate-800/80">
                  <div className="w-10 h-10 rounded-full bg-gradient-to-tr from-violet-600 to-cyan-500 flex items-center justify-center font-bold text-white text-sm">
                    MH
                  </div>
                  <div>
                    <h4 className="text-sm font-bold text-white">Malik Hammad</h4>
                    <p className="text-[11px] text-slate-400">
                      Founder @ Malik Hammad Digital & NEXUS PULSE • 1st
                    </p>
                  </div>
                </div>

                <div className="text-sm text-slate-200 whitespace-pre-line leading-relaxed font-sans">
                  {linkedin.fullPostText}
                </div>

                {linkedin.hashtags && linkedin.hashtags.length > 0 && (
                  <div className="pt-2 flex flex-wrap gap-2 text-xs font-medium text-blue-400">
                    {linkedin.hashtags.map((h, i) => (
                      <span key={i}>{h.startsWith('#') ? h : `#${h}`}</span>
                    ))}
                  </div>
                )}
              </div>
            </div>
          )}

          {/* TAB 4: WHATSAPP / TELEGRAM */}
          {activeTab === 'whatsapp' && (
            <div className="space-y-6">
              <div className="flex items-center justify-between flex-wrap gap-3 pb-4 border-b border-slate-800">
                <div>
                  <h3 className="text-base font-bold text-white flex items-center gap-2">
                    <Send className="w-4 h-4 text-emerald-400" />
                    <span>WhatsApp Official Channel & Telegram Update</span>
                  </h3>
                  <p className="text-xs text-slate-400">
                    Executive summary with emoji bullets, bold highlights, and 1-click read URL.
                  </p>
                </div>

                <button
                  onClick={() => copyToClipboard(whatsapp.fullMessageText, 'wa-full')}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-emerald-950/40 border border-emerald-500/30 text-emerald-300 hover:bg-emerald-900/40 transition-colors"
                >
                  {copiedKey === 'wa-full' ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-emerald-400" />
                      <span>Copied Message!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5 text-emerald-400" />
                      <span>Copy WhatsApp Text</span>
                    </>
                  )}
                </button>
              </div>

              <div className="max-w-2xl mx-auto p-5 sm:p-6 rounded-2xl bg-[#0d1f18] border border-emerald-500/25 shadow-xl relative space-y-3">
                <div className="flex items-center justify-between text-xs text-emerald-400 pb-2 border-b border-emerald-900/50">
                  <span className="font-semibold flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                    NEXUS PULSE Official Channel
                  </span>
                  <span className="text-[11px] text-slate-400">Broadcast • Just now</span>
                </div>

                <div className="text-sm text-slate-100 whitespace-pre-line font-sans leading-relaxed">
                  {whatsapp.fullMessageText}
                </div>

                <div className="text-right text-[11px] text-emerald-400/70 pt-1">
                  ✓✓ Delivered
                </div>
              </div>
            </div>
          )}

          {/* TAB 5: LINKEDIN SLIDE CAROUSEL */}
          {activeTab === 'carousel' && (
            <CarouselDeckPreview
              slides={carousel.slides}
              deckTitle={carousel.deckTitle || data.sourceTitle}
            />
          )}

          {/* TAB 6: 60S REEL / SHORT SCRIPT */}
          {activeTab === 'video' && (
            <VideoScriptPreview script={videoScript} />
          )}

        </div>

      </div>

    </div>
  );
}
